.tmux/plugins/tpm:
  type: archive
  exact: true
  refreshPeriod: "672h"
  stripComponents: 1
  url: https://github.com/tmux-plugins/tpm/archive/master.tar.gz
.local/share/nvim/lazy/lazy.nvim:
  type: git-repo
  refreshPeriod: "672h"
  url: 'https://github.com/folke/lazy.nvim.git'
  clone.args:
    - "--filter=blob:none"
    - "--branch=stable"
