.tmux/plugins/tpm:
  type: archive
  exact: true
  refreshPeriod: "672h"
  stripComponents: 1
  url: https://github.com/tmux-plugins/tpm/archive/master.tar.gz
.local/share/nvim/site/pack/packer/start/packer.nvim:
  type: git-repo
  refreshPeriod: "672h"
  url: https://github.com/wbthomason/packer.nvim
  clone.args:
    - "--depth"
    - "1"
